#!/bin/bash

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade

sudo add-apt-repository -y ppa:webupd8team/java
sudo add-apt-repository -y ppa:webupd8team/sublime-text-2
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer
sudo add-apt-repository -y ppa:gilir/lubuntu
sudo add-apt-repository -y ppa:brandonsnider/gnome-mplayer-dev
sudo add-apt-repository -y ppa:tualatrix/next
sudo add-apt-repository -y ppa:finalterm/daily
sudo add-apt-repository -y ppa:ozcanesen/terra-terminal

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade

sudo apt-get -y install gstreamer0.10-plugins-ugly gstreamer0.10-ffmpeg libxine1-ffmpeg gxine mencoder libdvdread4 totem-mozilla icedax tagtool easytag id3tool lame nautilus-script-audio-convert libmad0 mpg321
sudo apt-get install -y w32codecs libdvdcss2
sudo apt-get install -y ubuntu-restricted-extras
sudo apt-get install -y oracle-java7-installer
sudo apt-get install -y icedtea6-plugin icedtea-plugin
sudo apt-get install -y vim g++ linuxdcpp mplayer guake vlc mplayer2 gparted
sudo apt-get install -y flashplugin-installer
sudo apt-get install -y eclipse codeblocks
sudo apt-get install -y sublime-text
sudo apt-get install -y unity-tweak-tool
sudo apt-get install -y synaptic
sudo apt-get install -y compizconfig-settings-manager compiz-plugins-extra
sudo apt-get install -y lm-sensors hddtemp psensor
sudo apt-get install -y qbittorrent
sudo apt-get install -y p7zip-rar p7zip-full unace unrar zip unzip sharutils rar uudeview mpack arj cabextract file-roller
sudo apt-get install -y grub-customizer
sudo apt-get install -y gnome-mplayer
sudo apt-get install -y ubuntu-tweak
sudo apt-get install -y apache2
sudo apt-get install -y mysql-server mysql-client mysql-testsuite mysql-workbench mysql-workbench-data mysql-common mysqltuner
sudo apt-get install -y php5-mysql
sudo apt-get install -y libmysql-ruby
sudo apt-get install -y phpmyadmin
sudo apt-get install -y agave
sudo apt-get install -y chromium-browser
sudo apt-get install -y wicd
sudo apt-get install -y toilet figlet
sudo apt-get install -y terminator
sudo apt-get install -y emacs23
sudo apt-get install -y web2py
sudo apt-get install -y gnome-do
sudo apt-get install -y skype
sudo apt-get install -y subversion
sudo apt-get install -y freeglut3 freeglut3-dev binutils-gold
sudo apt-get install -y google-chrome-stable
sudo apt-get install -y nbtscan wireshark
sudo apt-get install -y tilda
sudo apt-get install -y convertall
sudo apt-get install -y wine
sudo apt-get install -y diffpdf pdfmod
sudo apt-get install -y bpython pida idle idle3
sudo apt-get install -y meld
sudo apt-get install -y octave
sudo apt-get install -y git gitg qgit
sudo apt-get install -y ghex 
sudo apt-get install -y netbeans
sudo apt-get install -y gimp
sudo apt-get install -y drupal7
sudo apt-get install -y ruby
sudo apt-get install -y qtcreator
sudo apt-get install -y hugin 
sudo apt-get install -y comix 
sudo apt-get install -y kile texmaker 
sudo apt-get install -y kcolorchooser gpick gcolor2
sudo apt-get install -y deluge
sudo apt-get install -y pidgin
sudo apt-get install -y xchat
sudo apt-get install -y nautilus-dropbox
sudo apt-get install -y youtube-dl
sudo apt-get install -y gdisk
sudo apt-get install -y python-pip python-virtualenv python-setuptools python-imaging python-pythonmagick python-markdown python-textile python-docutils python-django python-pyramid
sudo apt-get install -y libapache2-mod-python
sudo apt-get install -y grub2-splashimages
sudo apt-get install -y curl libcurl3 libcurl3-dev php5-curl
sudo apt-get install -y erlang
sudo apt-get install -y unetbootin
sudo apt-get install -y yaws
sudo apt-get install -y redis-server
sudo apt-get install -y mongodb couchdb
sudo apt-get install -y tree
sudo apt-get install -y ffmpeg
sudo apt-get install -y keepassx password-gorilla
sudo apt-get install -y openvpn
sudo apt-get install -y finalterm
sudo apt-get install -y flex
sudo apt-get install -y mit-scheme racket geiser
sudo apt-get install -y kvm-ipxe aqemu kvm lvm2
sudo apt-get install -y libvirt-bin virt-manager virtualbox-qt
sudo apt-get install -y xen-hypervisor-4.2-i386 xen-system-i386 xen-utils-4.2 xen-utils-common xen-tools
sudo apt-get install -y mercurial
sudo apt-get install -y tomcat7 tomcat7-user tomcat7-admin
sudo apt-get install -y corkscrew
sudo apt-get install -y openssh-server
sudo apt-get install -y xclip
sudo apt-get install -y aptitude
sudo apt-get install -y tasksel
sudo apt-get install -y ceph ceph-deploy
sudo apt-get install -y php5-odbc php5-sybase tdsodbc
sudo apt-get install -y python-dev libmysqlclient-dev
sudo apt-get install -y testdisk
sudo apt-get install -y policycoreutils
sudo apt-get install -y mailman postfix
sudo apt-get install -y shutter
sudo apt-get install -y libxerces-c3.1 libxerces-c-dev libicu-dev
sudo apt-get install -y libxml++2.6-dev libxml++2.6-doc
sudo apt-get install -y nodejs
sudo apt-get install -y npm
sudo apt-get install -y erlang-manpages
sudo apt-get install -y gmail-notify
sudo apt-get install -y terra

#Look And Feel
sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper
sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
sudo add-apt-repository -y ppa:noobslab/themes
sudo add-apt-repository -y ppa:noobslab/icons
sudo add-apt-repository -y ppa:jolicloud-team/ppa
sudo add-apt-repository -y ppa:upubuntu-com/nitrux
sudo add-apt-repository -y ppa:upubuntu-com/icons2
sudo add-apt-repository -y ppa:noobslab/deepin-sc

sudo apt-get -y update

sudo apt-get install -y gnome cairo-dock
sudo apt-get install -y trevilla-icons
sudo apt-get install -y trevilla-themes
sudo apt-get install -y jolicloud-desktop-environment
sudo apt-get install -y nitruxos
sudo apt-get install -y inx-icons
sudo apt-get install -y ubuntu-sdk
sudo apt-get install -y deepin-software-center


#Ruby
sudo apt-get install -y ruby1.9.3
curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
sudo apt-get -y --no-install-recommends install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev libgdbm-dev ncurses-dev automake libtool bison subversion pkg-config libffi-dev
rvm install 1.9.3
rvm use 1.9.3 --default
rvm rubygems current
gem install rails

sudo apt-get clean

gsettings set com.canonical.indicator.session show-real-name-on-panel true
#sudo gedit /etc/default/apport # Change Apport to 0
sudo service apport stop


